language: cpp

services:
- docker

#
# Notice: when you set environment variables, remember to
# explicitly propagate them into a Docker container (see ci/do_travis_ci.sh)
#

env:
  global:
  # TravisCI doesn't support IPv6 (see https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)
  - BAZEL_EXTRA_TEST_OPTIONS="--test_env=ENVOY_IP_TEST_VERSIONS=v4only"

jobs:
  include:
  # build debian binary
  - stage: ci
    os: linux
    script:
    - ci/do_travis_ci.sh build
  # build centos binary
  - stage: ci
    os: linux
    env:
    - IMAGE_NAME=envoyproxy/envoy-build-centos
    # TODO(yskopets): `envoy-build-centos` images were not published until March 2019,
    #                 that is why it's not possible to use the same tag as for `envoy-build-ubuntu` yet
    - IMAGE_ID=latest
    script:
    - ci/do_travis_ci.sh build
  # build MacOS binary
  - stage: ci
    os: osx
    install:
    - envoy/ci/mac_ci_setup.sh
    script:
    - ci/do_mac_ci.sh build
  # test on debian
  - stage: ci
    os: linux
    script:
    - ci/do_travis_ci.sh test
  # test on MacOS
  - stage: ci
    os: osx
    install:
    - envoy/ci/mac_ci_setup.sh
    script:
    - ci/do_mac_ci.sh test
  # test coverage on debian
  - stage: ci
    os: linux
    script:
    - ci/do_travis_ci.sh coverage
