apiVersion: v1
kind: Namespace
metadata:
  name: konvoy-system
---
apiVersion: v1
kind: Service
metadata:
  name: konvoy-control-plane
  namespace: konvoy-system
spec:
  ports:
  - port: 5678
    name: grpc-xds
  - port: 5679
    name: http-xds
  - port: 5681
    name: http-api-server
  selector:
    app: konvoy-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konvoy-control-plane
  namespace: konvoy-system
  labels:
    app: konvoy-control-plane
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: konvoy-control-plane
  template:
    metadata:
      labels:
        app: konvoy-control-plane
    spec:
      containers:
      - name: control-plane
        image: "konvoy/konvoy-control-plane:latest"
        imagePullPolicy: IfNotPresent
        env:
          - name: KONVOY_ENVIRONMENT
            value: "kubernetes"
          - name: KONVOY_STORE_TYPE
            value: "kubernetes"
          - name: KONVOY_XDS_SERVER_GRPC_PORT
            value: "5678"
          - name: KONVOY_XDS_SERVER_HTTP_PORT
            value: "5679"
          - name: KONVOY_API_SERVER_PORT
            value: "5681"
        args:
        - run
        ports:
        - containerPort: 5678
        - containerPort: 5679
        - containerPort: 5681
        livenessProbe:
          httpGet:
            path: /healthy
            port: 5680
        readinessProbe:
          httpGet:
            path: /ready
            port: 5680
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
