apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
metadata:
  namespace: kuma-example
  name: web-to-backend
mesh: default
spec:
  sources:
  - match:
      service: web
      region: us-east-1
      version: v10
  destinations:
  - match:
        # NOTE: only `service` tag can be used here (in `universal` all TCP connections will have `127.0.0.1` as destination => it's not enough info to infer any other destination tags)
      service: backend
  conf:
  - weight: 90
    destination:
      service: backend
      region: us-east-1
      version: v2
  - weight: 10
    destination:
      service: backend
      version: v3
