#
# Sample Envoy configuration that includes Konvoy filter and Konvoy Kafka Connector
#
admin:
  # Support CPU Profiling
  profile_path: /tmp/envoy.prof
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  # Ingesting HTTP requests into Kafka in addition to normal processing
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: mockbin.org
                  cluster: service_mockbin
          http_filters:
          #
          # Konvoy filter to pipe HTTP request through a side car process (Kafka Connector)
          #
          - name: konvoy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.konvoy.v2alpha.Konvoy
              stat_prefix: konvoy-kafka-connector
              grpc_service:
                envoy_grpc:
                  cluster_name: konvoy_kafka_connector_side_car
              per_service_config:
                # Configuration specific to "Konvoy Kafka Connector"
                http_konvoy:
                  # If Envoy gets configured via a YAML/JSON file, one should use `google.protobuf.Struct`
                  # instead of `com.konghq.konvoy.kafka.connector.v1alpha.http.HttpRequestSourceConnector`.
                  "@type": type.googleapis.com/google.protobuf.Struct
                  value:
                    # Ingesting HTTP requests in addition to normal processing
                    topic: http-requests
                    mode: NON_BLOCKING
          - name: envoy.router
  # Ingesting HTTP requests into Kafka instead of normal processing
  - name: listener_1
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: mockbin.org
                  cluster: service_mockbin
          http_filters:
          #
          # Konvoy filter to pipe HTTP request through a side car process (Kafka Connector)
          #
          - name: konvoy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.konvoy.v2alpha.Konvoy
              stat_prefix: konvoy-kafka-connector
              grpc_service:
                envoy_grpc:
                  cluster_name: konvoy_kafka_connector_side_car
              per_service_config:
                # Configuration specific to "Konvoy Kafka Connector"
                http_konvoy:
                  # If Envoy gets configured via a YAML/JSON file, one should use `google.protobuf.Struct`
                  # instead of `com.konghq.konvoy.kafka.connector.v1alpha.http.HttpRequestSourceConnector`.
                  "@type": type.googleapis.com/google.protobuf.Struct
                  value:
                    # Ingesting HTTP requests instead of normal processing
                    topic: http-requests
                    mode: BLOCKING
                    direct_response:
                      status: 202 # Accepted
          - name: envoy.router
  clusters:
  #
  # Konvoy Kafka Connector deployed as a side car process
  #
  - name: konvoy_kafka_connector_side_car
    connect_timeout: 0.25s
    type: STATIC
    dns_lookup_family: V4_ONLY
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8780
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
  - name: service_mockbin
    connect_timeout: 5s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_mockbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mockbin.org
                port_value: 443
    tls_context:
      sni: mockbin.org
